name: Publish ofegplots to pypi

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    #if: startsWith(github.event.ref, 'refs/tags')

    steps:
      #if: startsWith(github.event.ref, 'refs/tags')
      - uses: actions/checkout@v1
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: uqyge
          password: ${{ secrets.pypi_password }}
